import{configured}from"./firebase.js";import{getCurrent}from"./poe-service.js";import{esc,date,registerSW}from"./utils.js";
const root=document.querySelector("#poe-content"),start=document.querySelector("#start"),mode=document.querySelector("#step-mode"),id=new URLSearchParams(location.search).get("id");let data=null,current=0;
const call=(label,value,cls="")=>value?`<div class="callout ${cls}"><strong>${label}</strong>${esc(value)}</div>`:"";
function stepHtml(s,i){return`<article class="procedure-step"><div class="step-number">${String(i+1).padStart(2,"0")}</div><div class="step-content"><h2>${esc(s.titulo)}</h2>${s.imagen?`<img class="step-image" src="${esc(s.imagen)}" alt="${esc(s.titulo)}" loading="lazy">`:""}<p>${esc(s.instruccion)}</p><div class="callouts">${call("⚠ PUNTO CRÍTICO",s.puntoCritico,"critical")}${call("✓ CALIDAD",s.calidad,"quality")}${call("⛨ SEGURIDAD",s.seguridad,"safety")}${call("! ADVERTENCIA",s.advertencia,"critical")}</div></div></article>`}
function render(){const{poe:p,revision:r,steps}=data;document.title=`${p.codigo} · Caborca POE`;root.innerHTML=`<section class="poe-cover"><p class="eyebrow">PROCEDIMIENTO OPERACIONAL ESTÁNDAR</p><span class="code">${esc(p.codigo)}</span><h1>${esc(p.nombre)}</h1><p>${esc(r.objetivo||"")}</p><div class="poe-cover-grid"><div><small>Área</small>${esc(p.area||"—")}</div><div><small>Máquina</small>${esc(p.maquina||"—")}</div><div><small>Revisión</small>${String(r.revision).padStart(2,"0")}</div><div><small>Vigencia</small>${date(r.fechaVigencia)}</div></div></section>${steps.map(stepHtml).join("")}`;start.disabled=!steps.length;start.title=steps.length?"Abrir el procedimiento paso a paso":"Este POE no contiene pasos"}
function showStep(){const s=data.steps[current],pct=Math.round((current+1)/data.steps.length*100);document.querySelector("#step-slide").innerHTML=`<p class="eyebrow">PASO ${current+1} DE ${data.steps.length}</p><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>${stepHtml(s,current)}`;document.querySelector("#progress-label").textContent=`${pct}%`;document.querySelector("#prev").disabled=current===0;document.querySelector("#next").textContent=current===data.steps.length-1?"Finalizar":"Siguiente"}
function openMode(){if(!data?.steps?.length)return;current=0;showStep();mode.hidden=false;document.body.classList.add("step-open");document.querySelector("#close-step").focus()}
function closeMode(){mode.hidden=true;document.body.classList.remove("step-open");start.focus()}
start.addEventListener("click",openMode);document.querySelector("#close-step").addEventListener("click",closeMode);document.querySelector("#prev").addEventListener("click",()=>{if(current>0){current--;showStep()}});document.querySelector("#next").addEventListener("click",()=>{if(current>=data.steps.length-1)closeMode();else{current++;showStep()}});mode.addEventListener("click",e=>{if(e.target===mode)closeMode()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!mode.hidden)closeMode()});
if(!configured||!id){root.innerHTML='<div class="empty"><h2>POE no disponible</h2><p>El enlace no contiene un código de procedimiento válido.</p></div>';start.disabled=true}else getCurrent(id).then(x=>{data=x;render()}).catch(e=>{console.error(e);root.innerHTML='<div class="empty"><h2>POE no disponible</h2><p>No existe una revisión vigente o no fue posible cargarla.</p></div>';start.disabled=true});window.addEventListener("offline",()=>document.querySelector("#offline").hidden=false);registerSW();
