import{db}from"./firebase.js";
import{collection,doc,getDoc,getDocs,query,where,orderBy,addDoc,serverTimestamp,runTransaction,writeBatch}from"https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
export async function listPublished(){const s=await getDocs(query(collection(db,"poes"),where("activo","==",true),where("estado","==","Vigente")));return s.docs.map(d=>({id:d.id,...d.data()}))}
export async function listAll(){const s=await getDocs(query(collection(db,"poes"),orderBy("updatedAt","desc")));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function readSteps(poeId,revisionId){const snap=await getDocs(query(collection(db,"poes",poeId,"revisions",revisionId,"steps"),orderBy("orden")));return Promise.all(snap.docs.map(async stepDoc=>{const step={id:stepDoc.id,...stepDoc.data()};if(step.hasImage){const image=await getDoc(doc(db,"poes",poeId,"revisions",revisionId,"steps",stepDoc.id,"images","main"));if(image.exists()){step.imagen=image.data().dataUrl;step.imageMeta={mimeType:image.data().mimeType,bytes:image.data().bytes,width:image.data().width,height:image.data().height}}}return step}))}
export async function getCurrent(id){const p=await getDoc(doc(db,"poes",id));if(!p.exists())throw Error("missing");const poe={id:p.id,...p.data()};if(!poe.activo||!poe.currentRevisionId)throw Error("unavailable");const r=await getDoc(doc(db,"poes",id,"revisions",poe.currentRevisionId));if(!r.exists()||r.data().status!=="Vigente")throw Error("unavailable");return{poe,revision:{id:r.id,...r.data()},steps:await readSteps(id,r.id)}}
function writeStep(batch,poeId,revisionId,stepId,step,orden,userId){const{imagenData,imagen,imageMeta,id,...content}=step,hasImage=Boolean(imagenData?.dataUrl||imagen);batch.set(doc(db,"poes",poeId,"revisions",revisionId,"steps",stepId),{...content,orden,hasImage},{merge:true});if(hasImage){const payload=imagenData||{dataUrl:imagen,...imageMeta};batch.set(doc(db,"poes",poeId,"revisions",revisionId,"steps",stepId,"images","main"),{...payload,kind:"main",updatedAt:serverTimestamp(),updatedBy:userId})}}
export async function saveDraft(data,steps,user){const id=data.id||data.codigo,revId=data.revisionId||"REV-01",batch=writeBatch(db);batch.set(doc(db,"poes",id),{codigo:data.codigo,nombre:data.nombre,area:data.area,proceso:data.proceso,maquina:data.maquina,puesto:data.puesto,activo:true,estado:data.estado||"Borrador",draftRevisionId:revId,updatedAt:serverTimestamp(),creadoPor:user.uid},{merge:true});batch.set(doc(db,"poes",id,"revisions",revId),{revision:Number(revId.replace(/\D/g,""))||1,status:"Borrador",objetivo:data.objetivo,alcance:data.alcance,elaboro:data.elaboro,reviso:data.reviso,aprobo:data.aprobo,fechaVigencia:data.vigencia,createdAt:serverTimestamp(),createdBy:user.uid},{merge:true});steps.forEach((s,i)=>writeStep(batch,id,revId,`STEP-${String(i+1).padStart(3,"0")}`,s,i+1,user.uid));batch.set(doc(collection(db,"auditLog")),{accion:"GUARDAR_BORRADOR",poeId:id,revisionId:revId,userId:user.uid,createdAt:serverTimestamp()});await batch.commit();return id}
export async function publish(id,user){await runTransaction(db,async tx=>{const pRef=doc(db,"poes",id),p=await tx.get(pRef);const revId=p.data().draftRevisionId||p.data().currentRevisionId||"REV-01",rRef=doc(db,"poes",id,"revisions",revId),r=await tx.get(rRef);if(!r.exists())throw Error("missing-revision");if(p.data().currentRevisionId&&p.data().currentRevisionId!==revId)tx.update(doc(db,"poes",id,"revisions",p.data().currentRevisionId),{status:"Obsoleto"});tx.update(rRef,{status:"Vigente",publishedAt:serverTimestamp(),publishedBy:user.uid});tx.update(pRef,{currentRevisionId:revId,draftRevisionId:null,estado:"Vigente",updatedAt:serverTimestamp()})});await addDoc(collection(db,"auditLog"),{accion:"PUBLICAR",poeId:id,userId:user.uid,createdAt:serverTimestamp()})}
export async function newRevision(id,user){const current=await getCurrent(id),n=current.revision.revision+1,revId=`REV-${String(n).padStart(2,"0")}`,batch=writeBatch(db);const{id:oldRevisionId,...revisionData}=current.revision;batch.set(doc(db,"poes",id,"revisions",revId),{...revisionData,revision:n,status:"Borrador",createdAt:serverTimestamp(),createdBy:user.uid,publishedAt:null,publishedBy:null});current.steps.forEach((s,i)=>writeStep(batch,id,revId,`STEP-${String(i+1).padStart(3,"0")}`,s,i+1,user.uid));batch.update(doc(db,"poes",id),{draftRevisionId:revId,estado:"En revisión",updatedAt:serverTimestamp()});batch.set(doc(collection(db,"auditLog")),{accion:"NUEVA_REVISION",poeId:id,revisionId:revId,userId:user.uid,createdAt:serverTimestamp()});await batch.commit()}
